language: generic

services:
  - docker

# don't patch script with mac compatibility when running on linux systems
before_script:
- rm patches/build-script/90-add-mac-compat.patch

script:
 - ./build-custom-kernel.sh

deploy:
  provider: releases
  edge: true
  file: stage/RPMS/x86_64/*.rpm
#  on:
#    tags: true
